name: Docker

on:
  workflow_dispatch:
  schedule:
    - cron: 0 0 * * *
  pull_request:
  push:
    branches:
      - main
  release:
    types: [published]
jobs:
  job1:
    name: Build Docker Image
    runs-on: ubuntu-20.04
    timeout-minutes: 180
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          tags: wamvtan/detic:latest
          no-cache: true
          push: ${{ github.event_name != 'pull_request' }}